### ISSUE TITLE
Type x is part of the declarations of 2 modules: TemplateModule and TemplateModule! Please consider moving x to a higher module that imports TemplateModule and TemplateModule.

### ISSUE THREAD

**Issue by JaredLinwood** [patrikx3/angular-compile#13]
Notice we have a similar issue at #11, but not entirely sure they're related. Let me know if they are though.

I have a catch-all route (**), acting as a sort of custom content management system. Works well when first accessed, but on return hits within the same full page load I'm getting:

_Type c is part of the declarations of 2 modules: TemplateModule and TemplateModule! Please consider moving c to a higher module that imports TemplateModule and TemplateModule._

I'm replacing the HTML content being used by p3x. Important part of the view is below:

`<div [p3x-compile]="model.html" [p3x-compile-ctx]="this"></div>`

The HTML retrieval happens within an ActivatedRoute.url.subscribe event on the catch-all route component. Config of actual module below:

```
    CompileModule.forRoot({
      module: {
        schemas: [
          CUSTOM_ELEMENTS_SCHEMA
        ],
        imports: [
          FormsModule,
          SharedModule
        ],
        declarations: [
          AccordionDirective
        ]
      }
    })
```

It seems to me that performing a hot-swap on the HTML is causing certain background processes to be re-wired.

Any help would be greatly appreciated. I've tried a few different ways to alleviate this error, so far with no luck whatsoever. Outside of forcing a full page refresh instead of a route change for every call.

**Comment by JaredLinwood** [comment]
Currently running 4.1.481-16

**Comment by JaredLinwood** [comment]
Yes, sadly. I just tried a reinstall via NPM to ensure I had the latest.

`"p3x-angular-compile": "^4.1.484-19"`

Same issue.

**Comment by JaredLinwood** [comment]
Thanks so much for helping so far! I tried forking that, getting this when I `grunt run`:

`WARNING in ./~/@angular/core/@angular/core.es5.js
5704:15-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (/Users/jared/Development/angular-compile/node_modules/webpack/lib/dependencies/ImportContextDependency.js:28:4)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/jared/Development/angular-compile/node_modules/webpack/lib/Compilation.js:672:24)
    at Compilation.finish (/Users/jared/Development/angular-compile/node_modules/webpack/lib/Compilation.js:535:9)
    at /Users/jared/Development/angular-compile/node_modules/webpack/lib/Compiler.js:491:16
    at /Users/jared/Development/angular-compile/node_modules/tapable/lib/Tapable.js:225:11
    at _addModuleChain (/Users/jared/Development/angular-compile/node_modules/webpack/lib/Compilation.js:481:11)
    at processModuleDependencies.err (/Users/jared/Development/angular-compile/node_modules/webpack/lib/Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)

WARNING in ./~/@angular/core/@angular/core.es5.js
5720:15-102 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (/Users/jared/Development/angular-compile/node_modules/webpack/lib/dependencies/ImportContextDependency.js:28:4)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/jared/Development/angular-compile/node_modules/webpack/lib/Compilation.js:672:24)
    at Compilation.finish (/Users/jared/Development/angular-compile/node_modules/webpack/lib/Compilation.js:535:9)
    at /Users/jared/Development/angular-compile/node_modules/webpack/lib/Compiler.js:491:16
    at /Users/jared/Development/angular-compile/node_modules/tapable/lib/Tapable.js:225:11
    at _addModuleChain (/Users/jared/Development/angular-compile/node_modules/webpack/lib/Compilation.js:481:11)
    at processModuleDependencies.err (/Users/jared/Development/angular-compile/node_modules/webpack/lib/Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)`

**Comment by JaredLinwood** [comment]
This replicates the issue perfectly also. Simply setting the HTML and then switching it out after a few seconds.

```
this.html = '<custom-component></custom-component>';
setTimeout(() => this.html = '<div></div>', 5000);
```

**Comment by JaredLinwood** [comment]
I don't have it within two modules at the moment though. The custom component is only registered against CompileModule. 

I did try moving it to a shared module and then importing that. No error, but also didn't run/use the component at all.

**Comment by JaredLinwood** [comment]
Didn't seem to trigger the components at all though. So it imported but didn't actually work.

**Comment by JaredLinwood** [comment]
Let me build a simple demo for you in a repo, might make more sense.

**Comment by JaredLinwood** [comment]
Okay, thanks. I'll give it another go and share a repo if it doesn't. Thanks for the help so far!

**Comment by JaredLinwood** [comment]
Yes, and as I said I'm doing the exact same thing but it's not working for me. Let me try again. Maybe I missed something the first time I did it.

**Comment by JaredLinwood** [comment]
Okay must be something I'm doing. Thanks so much for the help. I'll give it another shot.
