### ISSUE TITLE
ERROR in The given rootPath undefined is not a file of the program.

### ISSUE THREAD

**Issue by Kovy95** [patrikx3/angular-compile#33]
Hey,

I'm trying to use your library and when I import it in -> app.module.ts 

`import { CompileModule } from 'p3x-angular-compile';`

I get this error and my app stops working.

`ERROR in The given rootPath undefined is not a file of the program.`

Sometimes it throws more errors

```
ERROR in The given rootPath undefined is not a file of the program.

  ERROR in node_modules/p3x-angular-compile/src/CompileAttribute.ts:183:19 - error NG1001: @NgModule argument must be an object literal
    
    183         @NgModule(module)
                          ~~~~~~
    node_modules/p3x-angular-compile/src/CompileAttribute.ts:194:23 - error NG1010: selector must be a string
    
    194             selector: nextId(),
                              ~~~~~~~~

```
I'm trying to use it on Angular 9.0.0-rc.9.

**Comment by Kovy95** [comment]
Thanks, it seems this part starts works, but I get another error:

```
ERROR in ./node_modules/p3x-angular-compile/src/CompileAttribute.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: /home/kovy/Desktop/modeler/node_modules/p3x-angular-compile/src/CompileAttribute.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/kovy/Desktop/modeler/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:900:23)
    at /home/kovy/Desktop/modeler/node_modules/@ngtools/webpack/src/loader.js:41:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
ERROR in ./node_modules/p3x-angular-compile/src/CompileModule.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: /home/kovy/Desktop/modeler/node_modules/p3x-angular-compile/src/CompileModule.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/kovy/Desktop/modeler/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:900:23)
    at /home/kovy/Desktop/modeler/node_modules/@ngtools/webpack/src/loader.js:41:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
ERROR in ./src/app/form-builder/data-field/custom-data-field/custom-data-field.component.ngfactory.js
Module not found: Error: Can't resolve '../../../../../node_modules/p3x-angular-compile/src/CompileAttribute.ngfactory' in '/home/kovy/Desktop/modeler/src/app/form-builder/data-field/custom-data-field'
```

Can you tell me if its a problem on my PC or you just need to update a library to APF 9?

**Comment by Kovy95** [comment]
I think it's related to Angular 9 and its linter because I got another error:

```
ERROR in Unexpected value 'CompileModule in /home/kovy/Desktop/modeler/node_modules/p3x-angular-compile/dist/src/CompileModule.js' imported by the module 'FormBuilderModule in /home/kovy/Desktop/modeler/src/app/form-builder/form-builder.module.ts'. Please add a @NgModule annotation.
Can't bind to 'p3x-compile' since it isn't a known property of 'span'. ("<span [ERROR ->][p3x-compile]="template" [p3x-compile-ctx]="this"></span>
")
Can't bind to 'p3x-compile-ctx' since it isn't a known property of 'span'. ("<span [p3x-compile]="template" [ERROR ->][p3x-compile-ctx]="this"></span>
")
```
I got that point it is good to wait for stable release of Angular 9 but I start building my app 2 weeks ago so i choose Angular 9 as start in Angular :)

**Comment by Kovy95** [comment]
> the error is: Please add a @NgModule annotation....

It seems more that your annotation of module missing, because when I remove CompileModule from imports array in my module, this error doesn't show me again. 
![image](https://user-images.githubusercontent.com/33829173/72820460-47b06380-3c6f-11ea-95cd-d034d9dc37c4.png)
I trying to find the definition of CompileModule in typescript (usually in <nameOfFile>.d.ts) but I don't find it, also when I trying to click on CompileModule in my imports its don't provide me the module function.

**Comment by Kovy95** [comment]
Now I can click on it and I see the functions, but there is still the same error 
![image](https://user-images.githubusercontent.com/33829173/72822586-a3c8b700-3c72-11ea-8c41-4f27282559e7.png)

**Comment by Kovy95** [comment]
Thank you very much, its works from version 107 :)
