### ISSUE TITLE
In Angular CLI: 10.0.3 wont compile

### ISSUE THREAD

**Issue by anjiJaUz** [patrikx3/angular-compile#37]
Dear Patrikx

Please advice what is the problem i am having using this plugin and how to resolve it.

For "tsconfig.json" i copied this file:

https://github.com/patrikx3/angular-compile/blob/master/tsconfig.json

My sample app is compiled like this:
Compiling @angular/animations : es2015 as esm2015

This plugin is being compiled like this:
Compiling p3x-angular-compile : main as esm5

Is the problem with two different ways of compiling?
How do we stop them compile in different ways?

Here is the data and the error message:

========================================================================
========================================================================
========================================================================
Angular CLI: 10.0.3
Node: 12.18.1
OS: win32 x64

Angular: 10.0.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.3
@angular-devkit/build-angular     0.1000.3
@angular-devkit/build-optimizer   0.1000.3
@angular-devkit/build-webpack     0.1000.3
@angular-devkit/core              10.0.3
@angular-devkit/schematics        10.0.3
@angular/cli                      10.0.3
@ngtools/webpack                  10.0.3
@schematics/angular               10.0.3
@schematics/update                0.1000.3
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0

========================================================================
========================================================================
========================================================================

here is how my sample app was first compiled:

C:\dev\angular\clitest\myapp>ng serve
Compiling @angular/animations : es2015 as esm2015
Compiling @angular/core : es2015 as esm2015
Compiling @angular/animations/browser : es2015 as esm2015
Compiling @angular/animations/browser/testing : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/common/http : es2015 as esm2015
Compiling @angular/common/http/testing : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/platform-browser/animations : es2015 as esm2015
Compiling @angular/core/testing : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling @angular/platform-browser/testing : es2015 as esm2015
Compiling @angular/compiler/testing : es2015 as esm2015
Compiling @angular/platform-browser-dynamic/testing : es2015 as esm2015
Compiling @angular/common/testing : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
Compiling @angular/router/testing : es2015 as esm2015

========================================================================
========================================================================
========================================================================

C:\dev\angular\clitest\myapp>npm install --save p3x-angular-compile
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ p3x-angular-compile@2020.4.208
added 1 package from 1 contributor, removed 1 package and audited 1460 packages in 26.227s

57 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

========================================================================
========================================================================
========================================================================

C:\dev\angular\clitest\myapp>ng serve --aot=false
Compiling p3x-angular-compile : main as esm5
Warning: Invalid constructor parameter decorator in C:/dev/angular/clitest/myapp/node_modules/p3x-angular-compile/dist/src/CompileAttribute.js:
 () => [
    { type: Compiler }
]
Error: The given rootPath undefined is not a file of the program.
    at getRootFileOrFail (C:\dev\angular\clitest\myapp\node_modules\@angular\compiler-cli\ngcc\src\host\esm2015_host.js:2324:19)
    at Esm5ReflectionHost.Esm2015ReflectionHost.computePublicDtsDeclarationMap (C:\dev\angular\clitest\myapp\node_modules\@angular\compiler-cli\ngcc\src\host\esm2015_host.js:1648:27)
    at Esm5ReflectionHost.Esm2015ReflectionHost.getDtsDeclaration (C:\dev\angular\clitest\myapp\node_modules\@angular\compiler-cli\ngcc\src\host\esm2015_host.js:458:53)
    at DelegatingReflectionHost.getDtsDeclaration (C:\dev\angular\clitest\myapp\node_modules\@angular\compiler-cli\ngcc\src\host\delegating_host.js:62:34)
    at Object.wrapTypeReference (C:\dev\angular\clitest\myapp\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\util.js:463:34)
    at Object.extractDirectiveMetadata (C:\dev\angular\clitest\myapp\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\directive.js:256:27)
    at ComponentDecoratorHandler.analyze (C:\dev\angular\clitest\myapp\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:145:47)
    at NgccTraitCompiler.TraitCompiler.analyzeTrait (C:\dev\angular\clitest\myapp\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:346:40)
    at analyze (C:\dev\angular\clitest\myapp\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:298:58)
    at _loop_1 (C:\dev\angular\clitest\myapp\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:320:21)
An unhandled exception occurred: NGCC failed.
See "C:\Users\User\AppData\Local\Temp\ng-as9nUL\angular-errors.log" for further details.

**Comment by anjiJaUz** [comment]
Thank you very much for prompt response.

So this is how i fixed original tsconfig.json:

{
  "files": [],
  "references": [
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.spec.json"
    }
  ]
// this is how i disable Ivy
  , "angularCompilerOptions": {
    "enableIvy": false
  }
}

and this is how i desable aot:

ng serve --aot=false

but still get the same error:

================================

C:\dev\angular\clitest\myapp>ng serve --aot=false
Compiling p3x-angular-compile : main as esm5
Warning: Invalid constructor parameter decorator in C:/dev/angular/clitest/myapp/node_modules/p3x-angular-compile/dist/src/CompileAttribute.js:
 () => [
    { type: Compiler }
]

================================

Or is there some other ways to disable aot and ivy?

I am so sorry to trouble you!

**Comment by anjiJaUz** [comment]
I am sorry to trouble you this much!
I was too dumb.
I managed disabling them as shown here:
https://angular.io/guide/ivy

that is:

in "angular.json"

...
            "aot": false,
...


and in "tsconfig.app.json";

...
  "angularCompilerOptions": {
    "enableIvy": false
  }
...

I am so sorry.

**Comment by anjiJaUz** [comment]
Yes, it is exactly what i did and it compiles nicely!
Thank you very much!
