### ISSUE TITLE
Directive not found during Compile

### ISSUE THREAD

**Issue by CarstenLeue** [patrikx3/angular-compile#8]
Hi @patrikx3 

I have moved to your new angular-compile module. Thanks again for your great work!

I run into the following issue which is probably dues to my lack of expertise in Angular 4:
- I have written a custom directive called "appDynamicImage"
- in my dynamically loaded markup I use it like this "<img class="card-img-top" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" alt="{{context.card.elements.personname.value}}" **[appDynamicImage]**="context.card.context.hub.apiUrl.origin + context.card.elements.image.renditions.default.url">

However the compilation step fails with an error (see below). I assume that this is because of a missing import, but I cannot figure out how to correctly declare the import.

Error:
ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'appDynamicImage' since it isn't a known property of 'img'. ("GODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" alt="{{context.card.elements.personname.value}}" [ERROR ->][appDynamicImage]="context.card.context.hub.apiUrl.origin + context.card.elements.image.renditions.de"): ng:///TemplateModule/TemplateComponent.html@1:158
Error: Template parse errors:
Can't bind to 'appDynamicImage' since it isn't a known property of 'img'. ("GODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" alt="{{context.card.elements.personname.value}}" [ERROR ->][appDynamicImage]="context.card.context.hub.apiUrl.origin + context.card.elements.image.renditions.de"): ng:///TemplateModule/TemplateComponent.html@1:158
    at syntaxError (http://localhost:4200/vendor.bundle.js:28149:34)
    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:38640:19)
    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:52391:39)
    at http://localhost:4200/vendor.bundle.js:52315:62
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:52315:19)
    at createResult (http://localhost:4200/vendor.bundle.js:52221:19)
    at ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:3043:26)
    at Object.onInvoke (http://localhost:4200/vendor.bundle.js:4799:37)
    at ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:3042:32)
    at syntaxError (http://localhost:4200/vendor.bundle.js:28149:34)
    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:38640:19)
    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:52391:39)
    at http://localhost:4200/vendor.bundle.js:52315:62
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:52315:19)

I tried:

imports: any[] = [DynamicImageDirective];

but this fails with:
core.es5.js:1084 ERROR Error: Uncaught (in promise): Error: Unexpected directive 'DynamicImageDirective' imported by the module 'TemplateModule'. Please add a @NgModule annotation.
Error: Unexpected directive 'DynamicImageDirective' imported by the module 'TemplateModule'. Please add a @NgModule annotation.

Would you be able to help?

**Comment by CarstenLeue** [comment]
This also happens for built-in directives, such as:

<div *nfIg="context.card" class="card mt-4">

Can't bind to 'nfIg' since it isn't a known property of 'div'. ("<div [ERROR ->]*nfIg="context.card" class="card mt-4">
